# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import inductive as inductive, constructor as constructor, Index as Index, induct as induct, absurd as absurd, dependent as dependent, theorem as theorem, hole as hole, axiom as axiom, record as record, Type as Type, Nat as Nat, Z as Z, S as S, Vec as Vec, VNil as VNil, VCons as VCons, Fin as Fin, FZ as FZ, FS as FS, Eq as Eq, refl as refl, J as J, nat_elim as nat_elim, vec_elim as vec_elim, fin_elim as fin_elim, record_elim as record_elim, ann as ann, lam as lam, implicit_lam as implicit_lam, ImplicitPi as ImplicitPi, vnil as vnil, vcons as vcons, pair as pair, fin0_elim as fin0_elim, Pi as Pi, Sigma as Sigma, Pair as Pair
from deppy.tactics import intro as intro, exact as exact, apply as apply, rewrite as rewrite, rewrite_in as rewrite_in, cases as cases, induction as induction
from deppy.equality import sym as sym, trans as trans, cong as cong, cong2 as cong2, transport as transport, transport_refl as transport_refl, transport_trans as transport_trans
from deppy.nat import add as add, mul as mul, add_zero as add_zero, add_succ as add_succ, add_assoc as add_assoc, add_comm as add_comm, add_swap as add_swap, mul_zero as mul_zero, mul_one as mul_one, mul_add_right as mul_add_right, pred_or as pred_or, succ_injective as succ_injective, add_left_cancel as add_left_cancel, add_right_cancel as add_right_cancel
from deppy.fin import fin_case as fin_case
