
# Compiler primitives. @builtin declarations are checked by the module loader.
# Their implementation and typing rules live in the frontend. Annotations on
# compiler forms document their surface API; the loader does not type-check them.
# `object` marks forms whose type depends on syntax or a checked declaration.

@builtin
def inductive(*args: object, **kwargs: object) -> object: ...

@builtin
def constructor(*args: object, **kwargs: object) -> object: ...

@builtin
class Index[T: Type]: ...

@builtin
def induct(level: int, value: object, motive: object, *branches: object) -> object: ...

@builtin
def absurd[A: Type](type: A, value: object) -> A: ...

@builtin
def verified(*args: object, **kwargs: object) -> object: ...

@builtin
class Refined[A: Type, predicate: object]: ...

@builtin
def verified_spec(function: object, *args: object) -> object: ...

@builtin
def invariant(*args: object, **kwargs: object) -> object: ...

@builtin
def decreases(*args: object, **kwargs: object) -> object: ...

@builtin
def dependent(*args: object, **kwargs: object) -> object: ...

@builtin
def theorem(*args: object, **kwargs: object) -> object: ...

@builtin
def hole(name: str) -> object: ...

@builtin
def axiom(*args: object, **kwargs: object) -> object: ...

@builtin
def record(*args: object, **kwargs: object) -> object: ...

@builtin
class Type: ...

@builtin
class Nat: ...

@builtin
def Z() -> Nat: ...

@builtin
def S(n: Nat) -> Nat: ...

@builtin
class Vec[A: Type, n: Nat]: ...

@builtin
def VNil[A: Type]() -> Vec[A, 0]: ...

@builtin
def VCons[A: Type](k: Nat, head: A, tail: Vec[A, k]) -> Vec[A, S(k)]: ...

@builtin
class Fin[n: Nat]: ...

@builtin
def FZ(k: Nat) -> Fin[S(k)]: ...

@builtin
def FS(k: Nat, pred: Fin[k]) -> Fin[S(k)]: ...

@builtin
class Eq[A: Type, x: A, y: A]: ...

@builtin
def refl[A: Type](value: A) -> Eq[A, value, value]: ...

@builtin
def J(level: int, type: Type, start: object, motive: object, base: object, end: object, proof: object) -> object: ...

@builtin
def nat_elim(level: int, motive: object, zero: object, succ: object, value: Nat) -> object: ...

@builtin
def vec_elim(level: int, type: Type, motive: object, nil: object, cons: object, size: Nat, value: object) -> object: ...

@builtin
def fin_elim(level: int, motive: object, zero: object, succ: object, size: Nat, value: object) -> object: ...

@builtin
def record_elim(level: int, motive: object, branch: object, value: object) -> object: ...

@builtin
def ann[A: Type](value: A, type: Type) -> A: ...

@builtin
def lam(domain: Type, body: object) -> object: ...

@builtin
def implicit_lam(domain: Type, body: object) -> object: ...

@builtin
class ImplicitPi[domain: Type, codomain: object]: ...

@builtin
def vnil[A: Type](type: A) -> Vec[A, 0]: ...

@builtin
def vcons[A: Type](type: A, length: Nat, head: A, tail: Vec[A, length]) -> Vec[A, S(length)]: ...

@builtin
def pair(type: Type, first: object, second: object) -> Pair: ...

@builtin
def fin0_elim[A: Type](*args: object) -> A: ...

@builtin
class Pi[domain: Type, codomain: object]: ...

@builtin
class Sigma[domain: Type, codomain: object]: ...

@builtin
class Pair: ...
