# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import dependent as dependent, theorem as theorem, Nat as Nat, Z as Z, S as S, Eq as Eq, refl as refl, Sigma as Sigma, Pair as Pair, Pi as Pi, absurd as absurd
from deppy.nat import add as add, mul as mul, pred_or as pred_or, add_zero as add_zero, add_comm as add_comm, add_succ as add_succ
from deppy.nat_order import LE as LE, LT as LT, LEZero as LEZero, LESucc as LESucc, pred_lt as pred_lt, le_trans as le_trans, le_weaken as le_weaken, le_refl as le_refl, le_decide as le_decide, lt_decide as lt_decide
from deppy.equality import cong as cong, sym as sym, trans as trans, transport as transport
from deppy.data import Bool as Bool, True_ as True_, False_ as False_, Empty as Empty
from deppy.bool import select as select, decision_true_intro as decision_true_intro, false_ne_true as false_ne_true, select_post_eq as select_post_eq, bool_not as bool_not
from deppy.nat_bool import nat_eq as nat_eq, nat_le as nat_le, nat_lt as nat_lt, nat_lt_true as nat_lt_true, is_zero as is_zero, equal_step as equal_step, equal as equal, zero_equal as zero_equal, step_equal as step_equal, equal_true as equal_true, equal_refl as equal_refl, equal_false as equal_false
sub_count: Any
sub: Any
sub_add: Any
divmod_step: Any
divmod: Any
quotient: Any
remainder: Any
sub_bound: Any
pred_le: Any
sub_le: Any
zero_strict: Any
le_strict: Any
divmod_step_bound: Any
divmod_bound: Any
remainder_lt_true: Any
divmod_wrap: Any
divmod_step_equation: Any
divmod_equation: Any
divisor_positive: Any
nonzero_positive: Any
unequal_zero_positive: Any
