# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import dependent as dependent, theorem as theorem, induct as induct, Pi as Pi, Type as Type, Eq as Eq, refl as refl, absurd as absurd
from deppy.data import Bool as Bool, False_ as False_, True_ as True_, Empty as Empty, Unit as Unit, MkUnit as MkUnit, Decidable as Decidable, Yes as Yes, No as No
from deppy.equality import sym as sym, transport as transport
negate: Any
is_true: Any
conjunction: Any
disjunction: Any
xor: Any
true_ne_false: Any
eq_decide: Any
is_true_intro: Any
is_true_elim: Any
negate_involutive: Any
conjunction_identity: Any
conjunction_annihilator: Any
conjunction_idempotent: Any
conjunction_complement: Any
conjunction_comm: Any
conjunction_assoc: Any
disjunction_identity: Any
disjunction_annihilator: Any
disjunction_idempotent: Any
disjunction_complement: Any
disjunction_comm: Any
disjunction_assoc: Any
negate_conjunction: Any
conjunction_absorption: Any
conjunction_distrib: Any
negate_disjunction: Any
disjunction_absorption: Any
disjunction_distrib: Any
xor_self: Any
xor_comm: Any
decision_bool: Any
select: Any
select_post: Any
false_type: Any
false_ne_true: Any
decision_true: Any
select_post_eq: Any
bool_not: Any
bool_eq: Any
false_true_elim: Any
true_false_elim: Any
not_false: Any
and_left: Any
and_right: Any
decision_true_intro: Any
