# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import dependent as dependent, Type as Type, Pi as Pi, Eq as Eq, refl as refl, J as J
sym: Any
trans: Any
cong: Any
transport: Any
cong2: Any
transport_refl: Any
transport_trans: Any
