# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import dependent as dependent, theorem as theorem, Type as Type, Nat as Nat, S as S, Fin as Fin, FZ as FZ, FS as FS, Pi as Pi, Eq as Eq, refl as refl, absurd as absurd, fin0_elim as fin0_elim, nat_elim as nat_elim, fin_elim as fin_elim
from deppy.nat_order import LT as LT, LEZero as LEZero, LESucc as LESucc
from deppy.nat import succ_injective as succ_injective, zero_ne_succ as zero_ne_succ
from deppy.equality import sym as sym, cong as cong
case_motive: Any
fin_case: Any
to_nat: Any
to_nat_lt: Any
to_nat_injective: Any
