# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import dependent as dependent, theorem as theorem, inductive as inductive, constructor as constructor, record as record, Index as Index, Type as Type, Pi as Pi, Sigma as Sigma, Pair as Pair, Nat as Nat, Eq as Eq, refl as refl, J as J, induct as induct, absurd as absurd
from deppy.lists import List as List, Nil as Nil, Cons as Cons, length as length, Mem as Mem, NoDup as NoDup, All as All, Any as Any, count as count, reject_head as reject_head, reject as reject, map as map, length_map as length_map, map_mem as map_mem, map_nodup as map_nodup, map_mem_reflect as map_injective_has, all_decide as all_decide, any_decide as any_decide, all_get as all_get, all_intro as all_intro, any_from_mem as any_from_mem, any_witness as any_witness, Removal as Removal, RemoveHere as RemoveHere, RemoveThere as RemoveThere, find_removal as find_removal
from deppy.data import Empty as Empty, Unit as Unit, MkUnit as MkUnit, Not as Not, Sum as Sum, Left as Left, Right as Right, Decidable as Decidable, Yes as Yes, No as No, decision_weight as decision_weight, weight_yes as weight_yes, weight_no as weight_no
from deppy.equality import sym as sym, trans as trans, cong as cong, transport as transport
from deppy.tactics import rewrite as rewrite, rewrite_in as rewrite_in
from deppy.nat import add as add, add_swap as add_swap
from deppy.functions import Bijection as Bijection, bijection_injective as bijection_injective
from deppy.data import Sum as Either, Decidable as Decision, MkUnit as Unit_
from deppy.lists import Mem as Has
class Enumeration:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, args: Any) -> Any: ...
finite_count: Any
finite_all_from_decision: Any
finite_all_decide: Any
finite_any_from_decision: Any
finite_any_decide: Any
finite_search: Any
bijection_enumeration: Any
bijection_cardinality: Any
either_elim: Any
removal_present: Any
removal_include: Any
removal_keep: Any
removal_nodup: Any
removal_absent: Any
removal_count: Any
tail_forward: Any
tail_backward: Any
SameCountAt: Any
same_count_nil: Any
same_count_step: Any
same_count: Any
map_has: Any
inverse_injective: Any
bijection_count: Any
count_map: Any
weight_unique: Any
weight_transport: Any
