# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import record as record, dependent as dependent, theorem as theorem, Type as Type, Pi as Pi, Sigma as Sigma, Pair as Pair, Eq as Eq, refl as refl
from deppy.equality import sym as sym, trans as trans, cong as cong
class Bijection:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, args: Any) -> Any: ...
identity_bijection: Any
inverse_bijection: Any
compose_bijection: Any
bijection_injective: Any
bijection_surjective: Any
