# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import inductive as inductive, constructor as constructor, Index as Index, induct as induct, absurd as absurd, dependent as dependent, Type as Type, Pi as Pi, Nat as Nat, Z as Z, S as S
class IVec:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, args: Any) -> Any: ...
class INil(IVec):
    def __init__(self) -> None: ...
class ICons(IVec):
    def __init__(self, k: Any, head: Any, tail: Any) -> None: ...
    k: Any
    head: Any
    tail: Any
class IFin:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, args: Any) -> Any: ...
class IFZ(IFin):
    def __init__(self, k: Any) -> None: ...
    k: Any
class IFS(IFin):
    def __init__(self, k: Any, pred: Any) -> None: ...
    k: Any
    pred: Any
case_motive: Any
fin_case: Any
get: Any
