# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import inductive as inductive, constructor as constructor, dependent as dependent, theorem as theorem, absurd as absurd, Nat as Nat, Z as Z, S as S, Eq as Eq, refl as refl
from deppy.equality import cong as cong
from deppy.data import Bool as Bool, False_ as False_, True_ as True_
from deppy.nat import add as nat_add, mul as nat_mul
from deppy.arithmetic import sub as nat_sub, divmod as nat_divmod
from deppy.verified import verified as verified, Refined as Refined
from deppy.bool import select as select, bool_eq as bool_eq, false_ne_true as false_ne_true
from deppy.nat_bool import nat_eq as nat_eq, nat_le as nat_le, nat_lt as nat_lt, nat_eq_true as nat_eq_true
class Int:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, args: Any) -> Any: ...
class Pos(Int):
    def __init__(self, value: Any) -> None: ...
    value: Any
class Neg(Int):
    def __init__(self, predecessor: Any) -> None: ...
    predecessor: Any
of_nat: Any
negative_nat: Any
magnitude: Any
negative: Any
neg: Any
pred_nat: Any
pred: Any
difference: Any
add: Any
sub: Any
mul: Any
le: Any
lt: Any
eq: Any
quotient: Any
remainder: Any
to_nat: Any
eq_true: Any
