# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import inductive as inductive, constructor as constructor, Index as Index, dependent as dependent, theorem as theorem, Type as Type, Pi as Pi, Sigma as Sigma, Pair as Pair, Nat as Nat, Z as Z, S as S, Eq as Eq, refl as refl, absurd as absurd
from deppy.equality import cong as cong, trans as trans, sym as sym, transport as transport
from deppy.data import Empty as Empty, Unit as Unit, MkUnit as MkUnit, Sum as Sum, Left as Left, Right as Right, Not as Not, Decidable as Decidable, Yes as Yes, No as No, sum_elim as sum_elim, decide_and as decide_and, decide_or as decide_or, decision_weight as decision_weight
from deppy.nat import add as add, add_succ as add_succ
from deppy.nat_order import LE as LE, LEZero as LEZero, LESucc as LESucc, le_step as le_step
class List:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, args: Any) -> Any: ...
class Nil(List):
    def __init__(self) -> None: ...
class Cons(List):
    def __init__(self, head: Any, tail: Any) -> None: ...
    head: Any
    tail: Any
length: Any
Mem: Any
NoDup: Any
All: Any
Any: Any
all_get: Any
all_intro: Any
any_from_mem: Any
any_witness: Any
all_decide: Any
any_decide: Any
search: Any
append: Any
mem_append_left: Any
mem_append_right: Any
mem_append_cases: Any
map: Any
append_assoc: Any
map_identity: Any
map_composition: Any
length_append: Any
length_map: Any
map_append: Any
snoc: Any
reverse: Any
snoc_append: Any
append_right_nil: Any
reverse_append: Any
map_snoc: Any
map_reverse: Any
length_snoc: Any
length_reverse: Any
reverse_snoc: Any
reverse_involution: Any
filter_head: Any
filter: Any
filter_mem_head: Any
filter_mem: Any
filter_head_mem_here: Any
filter_head_mem_tail: Any
filter_mem_intro: Any
filter_nodup_head: Any
filter_nodup: Any
count: Any
length_filter_head: Any
length_filter_eq_count: Any
count_head_le: Any
count_le_length: Any
length_filter_le: Any
reject_head: Any
reject: Any
count_split_head: Any
count_split: Any
class Removal:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, args: Any) -> Any: ...
class RemoveHere(Removal):
    def __init__(self, tail: Any) -> None: ...
    tail: Any
class RemoveThere(Removal):
    def __init__(self, head: Any, ys: Any, zs: Any, step: Any) -> None: ...
    head: Any
    ys: Any
    zs: Any
    step: Any
find_removal: Any
removal_mem: Any
removal_length: Any
map_mem: Any
map_mem_reflect: Any
map_nodup: Any
