# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import dependent as dependent, theorem as theorem, Type as Type, Nat as Nat, Z as Z, S as S, nat_elim as nat_elim, Eq as Eq, refl as refl
from deppy.equality import sym as sym, trans as trans, cong as cong, cong2 as cong2, transport as transport
from deppy.data import Empty as Empty, Unit as Unit, MkUnit as MkUnit
add: Any
mul: Any
add_zero: Any
add_succ: Any
add_assoc: Any
add_comm: Any
add_swap: Any
mul_zero: Any
mul_one: Any
mul_add_right: Any
mul_succ_left: Any
zero_mul: Any
zero_shape: Any
zero_ne_succ: Any
mul_comm: Any
mul_add_left: Any
mul_assoc: Any
pred_or: Any
succ_injective: Any
add_left_cancel: Any
add_right_cancel: Any
