# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import dependent as dependent, theorem as theorem, Nat as Nat, Z as Z, S as S, Type as Type, Pi as Pi, Eq as Eq, refl as refl, absurd as absurd
from deppy.equality import cong as cong, sym as sym, trans as trans, transport as transport
from deppy.data import Bool as Bool, False_ as False_, True_ as True_, Empty as Empty
from deppy.bool import decision_bool as decision_bool, decision_true as decision_true, decision_true_intro as decision_true_intro, select as select, bool_not as bool_not, not_false as not_false, and_left as and_left, and_right as and_right, false_ne_true as false_ne_true
from deppy.nat import pred_or as pred_or
from deppy.nat_order import pred_lt as pred_lt, LE as LE, LT as LT, le_decide as le_decide, lt_decide as lt_decide, le_trans as le_trans, le_weaken as le_weaken, le_antisymm as le_antisymm, le_refl as le_refl
nat_le: Any
nat_lt: Any
nat_lt_true: Any
nat_le_true: Any
nat_lt_false_zero: Any
lt_le_bound: Any
pred_lt_true: Any
nat_eq: Any
nat_lt_not_false: Any
nat_eq_true: Any
nat_le_refl_true: Any
is_zero: Any
equal_step: Any
equal: Any
zero_equal: Any
step_equal: Any
equal_true: Any
equal_refl: Any
equal_false: Any
nat_eq_refl_true: Any
nat_eq_intro: Any
equal_intro: Any
same_boolean_from_true: Any
equal_nat_eq: Any
