# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import inductive as inductive, constructor as constructor, Index as Index, dependent as dependent, theorem as theorem, Nat as Nat, Z as Z, S as S, Type as Type, Pi as Pi, Eq as Eq, refl as refl, absurd as absurd
from deppy.data import Empty as Empty, Unit as Unit, MkUnit as MkUnit, Sum as Sum, Left as Left, Right as Right, Decidable as Decidable, Yes as Yes, No as No, sum_elim as sum_elim
from deppy.nat import add as add, add_comm as add_comm, add_zero as add_zero, pred_or as pred_or, mul as mul, mul_comm as mul_comm
from deppy.equality import cong as cong, sym as sym, transport as transport
class LE:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, args: Any) -> Any: ...
class LEZero(LE):
    def __init__(self, n: Any) -> None: ...
    n: Any
class LESucc(LE):
    def __init__(self, n: Any, m: Any, step: Any) -> None: ...
    n: Any
    m: Any
    step: Any
LT: Any
le_refl: Any
le_step: Any
le_pred: Any
le_trans: Any
not_succ_le_zero: Any
le_decide_succ: Any
le_decide_step: Any
le_decide: Any
lt_decide: Any
le_total_succ: Any
le_total: Any
lt_to_succ_le: Any
succ_le_to_lt: Any
lt_succ_to_le: Any
le_to_lt_succ: Any
zero_le_lt_or_eq: Any
le_lt_or_eq: Any
lt_succ_cases: Any
strong_induction_all: Any
strong_induction: Any
lt_irrefl: Any
le_weaken: Any
lt_trans: Any
le_zero_eq: Any
le_antisymm: Any
add_le_add_left: Any
add_le_add_right: Any
add_lt_add_right: Any
mul_le_mul_right: Any
mul_le_mul_left: Any
mul_lt_succ: Any
mul_lt_mul_left: Any
mul_lt_eq_absurd: Any
mul_left_cancel_pos: Any
pred_lt: Any
