# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import inductive as inductive, constructor as constructor, Index as Index, theorem as theorem, Type as Type, Pi as Pi, Nat as Nat, S as S, Eq as Eq, refl as refl, absurd as absurd, Pair as Pair
from deppy.equality import sym as sym, trans as trans, cong as cong
from deppy.data import Empty as Empty, Sum as Sum, Left as Left, Right as Right, sum_elim as sum_elim, MkUnit as MkUnit
from deppy.lists import List as List, Nil as Nil, Cons as Cons, Mem as Mem, NoDup as NoDup, length as length, map as map
class Permutation:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __class_getitem__(cls, args: Any) -> Any: ...
class PermNil(Permutation):
    def __init__(self) -> None: ...
class PermCons(Permutation):
    def __init__(self, x: Any, xs: Any, ys: Any, tail: Any) -> None: ...
    x: Any
    xs: Any
    ys: Any
    tail: Any
class PermSwap(Permutation):
    def __init__(self, x: Any, y: Any, xs: Any) -> None: ...
    x: Any
    y: Any
    xs: Any
class PermTrans(Permutation):
    def __init__(self, xs: Any, ys: Any, zs: Any, first: Any, second: Any) -> None: ...
    xs: Any
    ys: Any
    zs: Any
    first: Any
    second: Any
perm_refl: Any
perm_sym: Any
perm_trans: Any
perm_length: Any
swap_mem: Any
perm_mem: Any
perm_mem_back: Any
swap_nodup: Any
perm_nodup: Any
perm_map: Any
