# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

intro: Any
exact: Any
apply: Any
rewrite: Any
rewrite_in: Any
cases: Any
induction: Any
