# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import dependent as dependent, theorem as theorem, Type as Type, Pi as Pi, Nat as Nat, Z as Z, S as S, Vec as Vec, VNil as VNil, VCons as VCons, vnil as vnil, vcons as vcons, Fin as Fin, FZ as FZ, FS as FS, fin0_elim as fin0_elim, nat_elim as nat_elim, vec_elim as vec_elim, Eq as Eq, refl as refl
from deppy.equality import trans as trans, cong as cong, cong2 as cong2
from deppy.nat import add as add
from deppy.fin import fin_case as fin_case
get: Any
map: Any
get_map: Any
vec_case_motive: Any
vec_nil_case: Any
vec_cons_case: Any
vec_extensional: Any
append: Any
append_left_index: Any
append_right_index: Any
get_append_left: Any
get_append_right: Any
snoc: Any
reverse: Any
last: Any
weaken: Any
mirror: Any
mirror_last: Any
mirror_weaken: Any
mirror_involution: Any
get_snoc_last: Any
get_snoc_weaken: Any
reverse_get: Any
