# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import invariant as invariant, decreases as decreases, dependent as dependent, theorem as theorem, Sigma as Sigma, Type as Type, Pi as Pi, Nat as Nat, Z as Z, S as S, Eq as Eq, refl as refl, absurd as absurd
from deppy.data import Bool as Bool, False_ as False_, True_ as True_, Sum as Sum, Left as Left, Right as Right, sum_elim as sum_elim, Unit as Unit
from deppy.nat_order import LE as LE, LT as LT, le_refl as le_refl, le_pred as le_pred, le_trans as le_trans, pred_lt as pred_lt, lt_decide as lt_decide
from deppy.verified import select as select, select_post_eq as select_post_eq, nat_lt as nat_lt, nat_lt_true as nat_lt_true, and_left as and_left, and_right as and_right, decision_true_intro as decision_true_intro
from deppy.nat import add as add, pred_or as pred_or
iterate: Any
LoopVC: Any
iterate_invariant: Any
false_at_zero: Any
iterate_exit: Any
loop_correct: Any
outcome_post: Any
outcome_correct: Any
run: Any
run_correct: Any
range_sub: Any
range_next: Any
range_count_fuel: Any
range_count: Any
range_bound: Any
range_decrease: Any
positive_stride: Any
