# Generated by scripts/generate_python_stubs.py; do not edit.
# Import/completion surface; dependent types are checked by DepPy.
from typing import Any

from deppy._builtins import Refined as Refined, verified as verified, verified_spec as verified_spec, dependent as dependent, theorem as theorem, induct as induct, Pi as Pi, Type as Type, Nat as Nat, Z as Z, S as S, Eq as Eq, refl as refl, absurd as absurd
from deppy.data import Bool as Bool, False_ as False_, True_ as True_, Unit as Unit, MkUnit as MkUnit, Empty as Empty, Decidable as Decidable, Yes as Yes, No as No
from deppy.equality import transport as transport, sym as sym
from deppy.nat import add as add, mul as mul, pred_or as pred_or
from deppy.bool import and_left as _bool_and_left, and_right as _bool_and_right, bool_eq as _bool_bool_eq, bool_not as _bool_bool_not, decision_bool as _bool_decision_bool, decision_true as _bool_decision_true, decision_true_intro as _bool_decision_true_intro, false_ne_true as _bool_false_ne_true, false_true_elim as _bool_false_true_elim, false_type as _bool_false_type, not_false as _bool_not_false, select as _bool_select, select_post as _bool_select_post, select_post_eq as _bool_select_post_eq, true_false_elim as _bool_true_false_elim
from deppy.nat_bool import lt_le_bound as _nat_lt_le_bound, nat_eq as _nat_nat_eq, nat_eq_true as _nat_nat_eq_true, nat_le as _nat_nat_le, nat_le_refl_true as _nat_nat_le_refl_true, nat_le_true as _nat_nat_le_true, nat_lt as _nat_nat_lt, nat_lt_false_zero as _nat_nat_lt_false_zero, nat_lt_not_false as _nat_nat_lt_not_false, nat_lt_true as _nat_nat_lt_true, pred_lt_true as _nat_pred_lt_true
from deppy.nat_order import pred_lt as pred_lt, LE as LE, LT as LT, le_decide as le_decide, lt_decide as lt_decide, le_trans as le_trans, le_weaken as le_weaken, le_antisymm as le_antisymm, le_refl as le_refl
decision_bool: Any
nat_le: Any
nat_lt: Any
select: Any
select_post: Any
false_type: Any
false_ne_true: Any
decision_true: Any
select_post_eq: Any
nat_lt_true: Any
nat_le_true: Any
nat_lt_false_zero: Any
lt_le_bound: Any
pred_lt_true: Any
bool_not: Any
bool_eq: Any
nat_eq: Any
false_true_elim: Any
true_false_elim: Any
not_false: Any
nat_lt_not_false: Any
and_left: Any
and_right: Any
nat_eq_true: Any
decision_true_intro: Any
nat_le_refl_true: Any
