//! Function HIR examples: motives and induction hypotheses are generated by lowering.
use super::{cong, nat_add};
use crate::{
    lower::{Arm, Body, Function, Parameter, Pattern},
    Expr as E,
    Plicity::{Explicit, Implicit},
};
fn n(s: &str) -> E {
    E::name(s)
}
fn p(name: &str, ty: E) -> Parameter {
    Parameter {
        name: name.into(),
        plicity: Explicit,
        ty,
    }
}
fn type_parameter(level: u32) -> Parameter {
    Parameter {
        name: "A".into(),
        plicity: Implicit,
        ty: E::Universe(level),
    }
}
fn arm(pattern: Pattern, value: E) -> Arm {
    Arm {
        pattern,
        body: Body::Return(value),
    }
}
fn matched(scrutinee: &str, arms: Vec<Arm>) -> Body {
    Body::Match {
        scrutinee: scrutinee.into(),
        arms,
    }
}
pub fn add() -> Function {
    Function {
        parameters: vec![p("n", E::Nat), p("m", E::Nat)],
        result: E::Nat,
        decreases: "n".into(),
        motive_level: 0,
        body: matched(
            "n",
            vec![
                arm(Pattern::Zero, n("m")),
                arm(
                    Pattern::Succ("k".into()),
                    E::Recur(vec![n("k"), n("m")]).succ(),
                ),
            ],
        ),
    }
}
pub fn append(level: u32) -> Function {
    Function {
        parameters: vec![
            type_parameter(level),
            p("n", E::Nat),
            p("m", E::Nat),
            p("xs", E::vec(n("A"), n("n"))),
            p("ys", E::vec(n("A"), n("m"))),
        ],
        result: E::vec(n("A"), nat_add().app(n("n")).app(n("m"))),
        decreases: "xs".into(),
        motive_level: level,
        body: matched(
            "xs",
            vec![
                arm(Pattern::VNil, n("ys")),
                arm(
                    Pattern::VCons {
                        len: "k".into(),
                        head: "h".into(),
                        tail: "t".into(),
                    },
                    E::vcons(
                        n("A"),
                        nat_add().app(n("k")).app(n("m")),
                        n("h"),
                        E::Recur(vec![n("A"), n("k"), n("m"), n("t"), n("ys")]),
                    ),
                ),
            ],
        ),
    }
}
pub fn zero_right() -> Function {
    Function {
        parameters: vec![p("n", E::Nat)],
        result: E::eq(E::Nat, nat_add().app(n("n")).app(E::Zero), n("n")),
        decreases: "n".into(),
        motive_level: 0,
        body: matched(
            "n",
            vec![
                arm(Pattern::Zero, E::Zero.refl()),
                arm(
                    Pattern::Succ("k".into()),
                    cong(0, 0)
                        .app(E::lam("x", Explicit, Some(E::Nat), n("x").succ()))
                        .app(E::Recur(vec![n("k")])),
                ),
            ],
        ),
    }
}
/// Convert Fin n to its zero-based natural number by structural recursion.
pub fn fin_rank() -> Function {
    Function {
        parameters: vec![p("n", E::Nat), p("i", E::fin(n("n")))],
        result: E::Nat,
        decreases: "i".into(),
        motive_level: 0,
        body: matched(
            "i",
            vec![
                arm(Pattern::FZ("k".into()), E::Zero),
                arm(
                    Pattern::FS {
                        bound: "k".into(),
                        pred: "j".into(),
                    },
                    E::Recur(vec![n("k"), n("j")]).succ(),
                ),
            ],
        ),
    }
}

/// Vec matching generalizes i : Fin n; the cons branch then splits i.
pub fn get(level: u32) -> Function {
    Function {
        parameters: vec![
            type_parameter(level),
            p("n", E::Nat),
            p("xs", E::vec(n("A"), n("n"))),
            p("i", E::fin(n("n"))),
        ],
        result: n("A"),
        decreases: "xs".into(),
        motive_level: level,
        body: matched(
            "xs",
            vec![
                arm(Pattern::VNil, E::fin0_elim(n("A"), n("i"))),
                Arm {
                    pattern: Pattern::VCons {
                        len: "k".into(),
                        head: "h".into(),
                        tail: "t".into(),
                    },
                    body: matched(
                        "i",
                        vec![
                            arm(Pattern::FZ("bound0".into()), n("h")),
                            arm(
                                Pattern::FS {
                                    bound: "bound1".into(),
                                    pred: "j".into(),
                                },
                                E::Recur(vec![n("A"), n("k"), n("t"), n("j")]),
                            ),
                        ],
                    ),
                },
            ],
        ),
    }
}
