"""Derive editor import/completion stubs from the shared standard library.

No dependent typing rules are translated to Python's type system. Generated
constructors become visible to editors; callable DSL forms use Any deliberately.
Run with Python 3.14; --check reports stale artifacts without writing them.
"""
import ast
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / 'crates/deppy-python/stdlib/deppy'


def render(path):
    lines = ['# Generated by scripts/generate_python_stubs.py; do not edit.',
             '# Import/completion surface; dependent types are checked by DepPy.',
             'from typing import Any', '']
    for node in ast.parse(path.read_text()).body:
        if isinstance(node, ast.ImportFrom):
            names = ', '.join(f'{a.name} as {a.asname or a.name}' for a in node.names)
            lines.append(f'from {node.module} import {names}')
        elif isinstance(node, ast.FunctionDef) and node.name != 'builtin':
            lines.append(f'{node.name}: Any')
        elif isinstance(node, ast.ClassDef):
            base = '(int)' if node.name == 'Nat' else ''
            lines.extend([f'class {node.name}{base}:',
                          '    def __init__(self, *args: Any, **kwargs: Any) -> None: ...',
                          '    def __class_getitem__(cls, args: Any) -> Any: ...'])
            for declaration in node.body:
                if isinstance(declaration, ast.FunctionDef):
                    fields = [arg.arg for arg in declaration.args.args]
                    lines.append(f'class {declaration.name}({node.name}):')
                    lines.append('    def __init__(self' + ''.join(f', {f}: Any' for f in fields) + ') -> None: ...')
                    lines.extend(f'    {field}: Any' for field in fields)
    return '\n'.join(lines) + '\n'


def main():
    stale = []
    for path in sorted(PACKAGE.glob('*.py')):
        if path.name == '_runtime.py':
            continue
        output = path.with_suffix('.pyi')
        expected = render(path)
        if '--check' in sys.argv:
            if not output.exists() or output.read_text() != expected:
                stale.append(str(output.relative_to(ROOT)))
        else:
            output.write_text(expected)
    if stale:
        raise SystemExit('Stale Python stubs:\n' + '\n'.join(stale))


if __name__ == '__main__':
    main()
