use super::{Binding, Exports};

const BUILTINS: &[&str] = &[
    "intro",
    "exact",
    "apply",
    "rewrite",
    "rewrite_in",
    "cases",
    "induction",
    "inductive",
    "constructor",
    "Index",
    "induct",
    "absurd",
    "verified",
    "Refined",
    "verified_spec",
    "invariant",
    "decreases",
    "dependent",
    "theorem",
    "hole",
    "axiom",
    "record",
    "Type",
    "Nat",
    "Z",
    "S",
    "Vec",
    "VNil",
    "VCons",
    "Fin",
    "FZ",
    "FS",
    "Eq",
    "refl",
    "J",
    "nat_elim",
    "vec_elim",
    "fin_elim",
    "record_elim",
    "ann",
    "lam",
    "implicit_lam",
    "ImplicitPi",
    "vnil",
    "vcons",
    "pair",
    "fin0_elim",
    "Pi",
    "Sigma",
    "Pair",
];

fn builtin_names(module: &str) -> &'static [&'static str] {
    match module {
        "deppy.tactics" => &[
            "intro",
            "exact",
            "apply",
            "rewrite",
            "rewrite_in",
            "cases",
            "induction",
        ],
        "deppy._builtins" => BUILTINS,
        "deppy.core" => &[
            "dependent",
            "theorem",
            "hole",
            "axiom",
            "Type",
            "Pi",
            "ImplicitPi",
            "lam",
            "implicit_lam",
            "ann",
        ],
        "deppy.nat" => &["Nat", "Z", "S", "nat_elim"],
        "deppy.equality" => &["Eq", "refl", "J"],
        "deppy.sigma" => &["Sigma", "Pair", "pair"],
        "deppy.fin" => &["Fin", "FZ", "FS", "fin_elim", "fin0_elim"],
        "deppy.vectors" => &["Vec", "VNil", "VCons", "vnil", "vcons", "vec_elim"],
        "deppy.records" => &["record", "record_elim"],
        _ => &[],
    }
}

pub(super) fn builtin_exports(module: &str) -> Exports {
    builtin_names(module)
        .iter()
        .map(|name| ((*name).into(), Binding::builtin(name)))
        .collect()
}

pub(super) fn standard(name: &str) -> Option<&'static str> {
    match name {
        "deppy.tactics" => Some(include_str!("../../stdlib/deppy/tactics.py")),
        "deppy.integer" => Some(include_str!("../../stdlib/deppy/integer.py")),
        "deppy.arithmetic" => Some(include_str!("../../stdlib/deppy/arithmetic.py")),
        "deppy.verified_loop" => Some(include_str!("../../stdlib/deppy/verified_loop.py")),
        "deppy.verified" => Some(include_str!("../../stdlib/deppy/verified.py")),
        "deppy.naturals" => Some(include_str!("../../stdlib/deppy/naturals.py")),
        "deppy.indexed" => Some(include_str!("../../stdlib/deppy/indexed.py")),
        "deppy.data" => Some(include_str!("../../stdlib/deppy/data.py")),
        "deppy.logic" => Some(include_str!("../../stdlib/deppy/logic.py")),
        "deppy.lists" => Some(include_str!("../../stdlib/deppy/lists.py")),
        "deppy.nat_order" => Some(include_str!("../../stdlib/deppy/nat_order.py")),
        "deppy" => Some(include_str!("../../stdlib/deppy/__init__.py")),
        "deppy._builtins" => Some(include_str!("../../stdlib/deppy/_builtins.py")),
        "deppy.core" => Some(include_str!("../../stdlib/deppy/core.py")),
        "deppy.nat" => Some(include_str!("../../stdlib/deppy/nat.py")),
        "deppy.vectors" => Some(include_str!("../../stdlib/deppy/vectors.py")),
        "deppy.fin" => Some(include_str!("../../stdlib/deppy/fin.py")),
        "deppy.equality" => Some(include_str!("../../stdlib/deppy/equality.py")),
        "deppy.sigma" => Some(include_str!("../../stdlib/deppy/sigma.py")),
        "deppy.records" => Some(include_str!("../../stdlib/deppy/records.py")),
        _ => None,
    }
}
